# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

#import DataNodeService_pb2 as DataNodeService__pb2
from . import DataNodeService_pb2 as DataNodeService__pb2

class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreBlock = channel.stream_unary(
                '/protos.DataNodeService/StoreBlock',
                request_serializer=DataNodeService__pb2.StoreBlockRequest.SerializeToString,
                response_deserializer=DataNodeService__pb2.StatusRes.FromString,
                )
        self.ReadBlock = channel.unary_stream(
                '/protos.DataNodeService/ReadBlock',
                request_serializer=DataNodeService__pb2.ReadBlockRequest.SerializeToString,
                response_deserializer=DataNodeService__pb2.BlockData.FromString,
                )
        self.ReplicateBlock = channel.unary_unary(
                '/protos.DataNodeService/ReplicateBlock',
                request_serializer=DataNodeService__pb2.ReplicateBlockRequest.SerializeToString,
                response_deserializer=DataNodeService__pb2.StatusRes.FromString,
                )


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreBlock(self, request_iterator, context):
        """StoreBlock stores a continuous stream of blocks into the DataNode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """ReadBlock retrieves the data for a given block ID from the DataNode. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateBlock(self, request, context):
        """ReplicateBlock instructs the DataNode to replicate the specified block 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreBlock,
                    request_deserializer=DataNodeService__pb2.StoreBlockRequest.FromString,
                    response_serializer=DataNodeService__pb2.StatusRes.SerializeToString,
            ),
            'ReadBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=DataNodeService__pb2.ReadBlockRequest.FromString,
                    response_serializer=DataNodeService__pb2.BlockData.SerializeToString,
            ),
            'ReplicateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateBlock,
                    request_deserializer=DataNodeService__pb2.ReplicateBlockRequest.FromString,
                    response_serializer=DataNodeService__pb2.StatusRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/protos.DataNodeService/StoreBlock',
            DataNodeService__pb2.StoreBlockRequest.SerializeToString,
            DataNodeService__pb2.StatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protos.DataNodeService/ReadBlock',
            DataNodeService__pb2.ReadBlockRequest.SerializeToString,
            DataNodeService__pb2.BlockData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.DataNodeService/ReplicateBlock',
            DataNodeService__pb2.ReplicateBlockRequest.SerializeToString,
            DataNodeService__pb2.StatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
