# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataNodeService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44\x61taNodeService.proto\x12\x06protos\"-\n\tStatusRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\tBlockData\x12\x0f\n\x07\x62lockId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"5\n\x10ReadBlockRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x62lockId\x18\x02 \x01(\t\"K\n\x11StoreBlockRequest\x12$\n\tblockData\x18\x01 \x01(\x0b\x32\x11.protos.BlockData\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"V\n\x15ReplicateBlockRequest\x12$\n\tblockData\x18\x01 \x01(\x0b\x32\x11.protos.BlockData\x12\x17\n\x0f\x64\x61taNodeAddress\x18\x02 \x03(\t2\xcf\x01\n\x0f\x44\x61taNodeService\x12<\n\nStoreBlock\x12\x19.protos.StoreBlockRequest\x1a\x11.protos.StatusRes(\x01\x12:\n\tReadBlock\x12\x18.protos.ReadBlockRequest\x1a\x11.protos.BlockData0\x01\x12\x42\n\x0eReplicateBlock\x12\x1d.protos.ReplicateBlockRequest\x1a\x11.protos.StatusResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataNodeService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSRES']._serialized_start=33
  _globals['_STATUSRES']._serialized_end=78
  _globals['_BLOCKDATA']._serialized_start=80
  _globals['_BLOCKDATA']._serialized_end=122
  _globals['_READBLOCKREQUEST']._serialized_start=124
  _globals['_READBLOCKREQUEST']._serialized_end=177
  _globals['_STOREBLOCKREQUEST']._serialized_start=179
  _globals['_STOREBLOCKREQUEST']._serialized_end=254
  _globals['_REPLICATEBLOCKREQUEST']._serialized_start=256
  _globals['_REPLICATEBLOCKREQUEST']._serialized_end=342
  _globals['_DATANODESERVICE']._serialized_start=345
  _globals['_DATANODESERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
